name: 'Codeowners Labeler'
description: 'Adds labels to PRs based on the CODEOWNERS file'
author: 'mlabraca'
inputs:
  github_token:
    description: 'GitHub token to interact with GitHub API'
    required: true
runs:
  using: 'bash'
  main: './script.sh'