name: 'Codeowners Labeler'
description: 'Adds labels to PRs based on the CODEOWNERS file'
author: 'mlabraca'
inputs:
  github_token:
    description: 'GitHub token to interact with GitHub API'
    required: true
  codeowners_path:
    description: 'The CODEOWNERS file path'
    required: true
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CODEOWNERS_PATH: ${{ inputs.codeowners_path }}